[package]
name = "utils"
version = "0.6.0"
edition = "2024"

[dependencies]
reqwest = { version = "0.11", features = ["json"] }
ctrlc = "3.4.5"
serde = {version = "1.0.208", features = ["derive"]}
serde_json = "1.0.140"
