[package]
name = "utils"
version = "0.3.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11", features = ["json"] }
ctrlc = "3.4.5"
chrono = "0.4"
libc = "0.2.162"
rand = "0.8.5"
actix-rt = "2.10.0"
lazy_static = "1.5"
